export const theme = {
    typography: {
        h1Bold: {
            fontSize: '34px',
            lineHeight: '36px',
            fontWeight: 700,
            fontFamily: '"SB Sans Display", Helvetica, Arial, sans-serif',
            letterSpacing: '0.000px',
        },
        h2SemiBold: {
            fontSize: '28px',
            lineHeight: '32px',
            fontWeight: 600,
            fontFamily: '"SB Sans Display", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.280px',
        },
        h3SemiBold: {
            fontSize: '24px',
            lineHeight: '28px',
            fontWeight: 600,
            fontFamily: '"SB Sans Display", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.300px',
        },
        h4SemiBold: {
            fontSize: '20px',
            lineHeight: '24px',
            fontWeight: 600,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.300px',
        },
        h5SemiBold: {
            fontSize: '18px',
            lineHeight: '22px',
            fontWeight: 600,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.300px',
        },
        body1Regular: {
            fontSize: '16px',
            lineHeight: '20px',
            fontWeight: 400,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.288px',
        },
        body1SemiBold: {
            fontSize: '16px',
            lineHeight: '20px',
            fontWeight: 600,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.288px',
        },
        body2Regular: {
            fontSize: '14px',
            lineHeight: '18px',
            fontWeight: 400,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.252px',
        },
        body2SemiBold: {
            fontSize: '14px',
            lineHeight: '18px',
            fontWeight: 600,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.252px',
        },
        caption1Regular: {
            fontSize: '12px',
            lineHeight: '16px',
            fontWeight: 400,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.264px',
        },
        caption1SemiBold: {
            fontSize: '12px',
            lineHeight: '16px',
            fontWeight: 600,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '-0.264px',
        },
        caption2Regular: {
            fontSize: '10px',
            lineHeight: '14px',
            fontWeight: 400,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '0.120px',
        },
        caption2SemiBold: {
            fontSize: '10px',
            lineHeight: '14px',
            fontWeight: 600,
            fontFamily: '"SB Sans Text", Helvetica, Arial, sans-serif',
            letterSpacing: '0.120px',
        },
    },
    colors: {
        textPrimary: '#000000',
        textSecondary: '#939393',
        textError: '#dc3545',
        textAction: '#0d6efd',
        textSuccess: '#198754',
    },
    space: Array.from({ length: 25 }, (_, k) => k * 4),
};
